name: Compile Typst documents
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: delete "ignored" typst documents
        run: |
          while IFS= read -r f; do rm -r "documents/${f}"; done < .typstignore
      - name: typst compile
        run:  |
          docker run -e "XDG_CACHE_HOME=/root" --user $(id -u):$(id -g) -v ${{ github.workspace }}:/root --rm ghcr.io/typst/typst:latest find documents -type f -name "*\.typ" -exec typst compile --root . {} \;
      - name: set .pdf timestamps from .typ and delete .typ
        run: |
          shopt -s globstar
          for f in documents/**/*.typ; do
            touch -amd "$( date -R -r "$f" )" "${f%.typ}.pdf"
            rm "$f"
          done
      - name: checokut the builds repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/docs
          path: docs
          token: ${{secrets.PUSH_TOKEN}}
          fetch-depth: 0
      - name: push to builds repo
        run: |
          mv docs "${RUNNER_TEMP}"
          rsync -a --delete documents "${RUNNER_TEMP}/docs"
          pushd "${RUNNER_TEMP}/docs"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$(TZ=Europe/Rome date)"
          git push -f
        env:
          GITHUB_TOKEN: ${{ github.token }}
